### ISSUE TITLE
Integrate over bins

### ISSUE THREAD

**Issue by klieret** [celis/B_decays_clustering#4]
For the q2 spectra, we currently write out the differential dGamma/dq2 (normalized) at the q2 points. Shouldn't we integrate over the q2 bins to get the expectations for the 'bin contents'? [Obviously that's gonna be nearly equivalent for many bins of course]

I guess it would be best to define some function with the following signature

```py
def binDistribution(fct, bins, normalized=False)
    # fct is the function, bins is a list of the bin edgepoints
    # normalized on whether we should divide out the total integral from the 
    # lowest to highest binning point
```

**Comment by klieret** [comment]
this probably implements it

**Comment by klieret** [comment]
![image](https://user-images.githubusercontent.com/13602468/47403682-59157200-d785-11e8-8344-2fbc0330c432.png)

is what it looks like for the SM (two different bin widths)

**Comment by celis** [comment]
ok, looks good

**Comment by celis** [comment]
One thing, I am looking at the binning in distribution.py and I am confused.     We have as function  dGdq2 which is $\frac{dG}{dq^2}$, and we integrate it over a bin giving

$$ \int_{q_1^2}^{q_2^2} \frac{dG}{dq^2}  d q^2  =   ( \frac{dG}{dq^2} )_*  \Delta q^2    $$ 

where $()_*$ denotes the mean value in the interval and $ \Delta q^2  = q_2^2 - q_1^2$.   Then as bin_content I would write 

$$ ( \frac{dG}{dq^2} )_*  $$ 

This would be the current bin_content divided by $ \Delta q^2$

The normalization will still be given by the current expression.

**Comment by klieret** [comment]
I guess that's a bit of a convention issue, but from experimental physics I am used that a histograms shows the total count of events that fall in a certain bin (without normalizing that to the bin width), so that's what I'd call the 'bin content'.  Because that's what you'd see experimentally in a counting experiment.

**Comment by klieret** [comment]
no, they were with ``normalized=True`` (see the file ``plot_distribution.py``, which was just some quick ad-hoc script to plot them).

However I also just realized that using the ``plt.step`` like I did is not what you want (because it will build a step function from the bin midpoints, rather from the edges).

Also the normalization indeed doesn't seem to be right yet? 

I'll look into that tomorrow

**Comment by celis** [comment]
Hi, 
yes the normalization doesnt look right.  It seems to me from your implementation that the normalized curve should have integral equal to 1, unless I am missing something.  

Regards

**Comment by klieret** [comment]
That should fix it :)

**Comment by klieret** [comment]
![image](https://user-images.githubusercontent.com/13602468/47650931-1ad4e400-dbc5-11e8-8190-28f7a1c11cf4.png)

as created with the example script ``plot_distribution.py``.
